on:
  push:
    paths:
      - 'packages/basti-cdk/**'
      - '.github/workflows/basti-cdk-actions.yml'

jobs:
  test-basti-cdk:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [ 16.x, 18.x, 20.x ]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: npm ci
      - name: Run tests
        working-directory: packages/basti-cdk
        run: npm run test -w basti-cdk
